-- require("sayid.options")
-- require("sayid.keymaps")
-- require("sayid.plugins")
require("sayid.core")
require("sayid.colorscheme")
require("sayid.cmp")
require("sayid.lualine")
require("sayid.lsp")
require("sayid.telescope")
require("sayid.treesitter")
require("sayid.autopairs")
require("sayid.comment")
require("sayid.bufferline")
require("sayid.nvim-tree")
require("sayid.alpha")
require("sayid.barbar")
require("sayid.trouble")
require("sayid.toggleterm")
-- require("sayid.tabline")
